---
# Note: this is just an example on how the stack can be executed in a test
# setting, you may want to change it for your production use case.

# This file is handled automatically using the clouds-aws tool. It can be
# installed using pip, or from https://github.com/elias5000/clouds-aws
LambdaZipPath: dv/lambda_build_39d70ab.zip
LambdaHandlerFunction: handler.Handle
LambdaS3Bucket: cloudprowess-private
LambdaMemorySize: '256'
ExecutionFrequency: "rate(1 minute)"
MinOnDemandNumber: '1'
